/**********************************************************************
 * Extern for Waveform
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var Waveform = function () {};
Waveform.prototype = {
  "setData": function () {},
  "setDataInterpolated": function () {},
  "setDataCropped": function () {},
  "update": function () {},
  "redraw": function () {},
  "clear": function () {},
  "patchCanvasForIE": function () {},
  "createCanvas": function () {},
  "expandArray": function () {},
  "linearInterpolate": function () {},
  "interpolateArray": function () {},
  "optionsForSyncedStream": function () {},
  "dataFromSoundCloudTrack": function () {}
};
/**********************************************************************
 * End Generated Extern for Waveform
/**********************************************************************/
